apiVersion: v1
kind: Service
metadata:
  name: sample-nodeport
  namespace: slackbot
  annotations:
    cloud.google.com/load-balancer-type: Internal
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 3000
      targetPort: 3000
  selector:
    app: slackbot
